### ISSUE TITLE
Extension doesn't work anymore since last vscode update

### ISSUE THREAD

**Issue by VincentAbric** [stef-levesque/vscode-perforce#109]
Since VSCode 1.18 update, it's not possible to select the perforce extension in the Source Control window.
When trying to log into perforce using the command palette, I got the following error : `command 'perforce.login' not found`.
I tried other SMC extensions and they all behave the same way.

**Comment by stef-levesque** [comment]
This likely happen because `perforce.activationMode` is in `autodetect` (default), and no `.p4config` file could be found.
Some behavior had to change to support multi-root, but you can try one of the following:

Option 1) set `"perforce.activationMode": "always"` in your User Settings
With this setting on, the extension will always try to register the scmProvider, with or without a `.p4config` file, as long as a folder is opened.
Look at the `Source Control` section, and see if any Perforce provider is visible. The try to login from that menu
![image](https://user-images.githubusercontent.com/7251102/32673878-c206cd46-c61e-11e7-963d-e89c66384ac5.png)

---

Option 2) set your login information in settings
You can set your user, client, port and password information in your workspace or user settings.
Your password is optional, if you don't want to keep sensitive information in a text file. Then you password will be ask when you try to log in.
See [vscode-perforce - Configuration](https://github.com/stef-levesque/vscode-perforce#configuration) for more info.

---

Option 3) keep `"perforce.activationMode": "autodetect"` and create a `.p4config` file 
At the root of your workspace, create a `.p4config` file with the following:
```
P4USER=your_user
P4CLIENT=your_client
P4PORT=example.com:1666
```

Hope this helps.

**Comment by VincentAbric** [comment]
Hi,

Setting `"perforce.activationMode"` to `"always`" and adding my login info in the settings fixed my problem.
Thanks a lot!
