### ISSUE TITLE
Changelists appear twice

### ISSUE THREAD

**Issue by TheHolyWaffle** [stef-levesque/vscode-perforce#67]
Changelists appear twice, but the changed files sit in only a single changelist. See screenshot:

![vscode bug](https://cloud.githubusercontent.com/assets/787914/25439831/dda1e63e-2a9d-11e7-95aa-1defb0b924fe.PNG)

**Comment by stef-levesque** [comment]
Hm, what exact steps lead you to this?
Does hitting `Refresh` fix the issue?

**Comment by TheHolyWaffle** [comment]
Refresh doesnt fix it. I'll respond with the steps once I can reproduce it
accurately.

Op 26 apr. 2017 16:36 schreef "stef-levesque" <notifications@github.com>:

Hm, what exact steps lead you to this?
Does hitting Refresh fix the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stef-levesque/vscode-perforce/issues/67#issuecomment-297428505>,
or mute the thread

**Comment by ihalip** [comment]
I think this is a duplicate of #62. I've noticed the same thing happening when deleting regular files from the workspace. And yes, this isn't fixed by a Refresh.

In my case specifically, our build system does lots of work (creating & deleting files) in an intermediate directory. My workaround is to just add that intermediate directory to `files.exclude`.

**Comment by TheHolyWaffle** [comment]
Closing this issue as it is a duplicate of #62.
